function out1 = computegeometricpoppy(q1,q2,q3,q4)
%COMPUTEGEOMETRICPOPPY
%    OUT1 = COMPUTEGEOMETRICPOPPY(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    24-Jan-2016 15:29:35

t2 = cos(q2);
t3 = cos(q4);
t4 = sin(q2);
t5 = sin(q3);
t6 = sin(q4);
t7 = cos(q3);
t8 = cos(q1);
t9 = sin(q1);
t10 = t7.*t8;
t11 = t4.*t5.*t9;
t12 = t10+t11;
t13 = t7.*t9;
t15 = t4.*t5.*t8;
t14 = t13-t15;
out1 = reshape([t2.*t7,t5.*t8-t4.*t7.*t9,t5.*t9+t4.*t7.*t8,0.0,-t4.*t6-t2.*t3.*t5,t3.*t12-t2.*t6.*t9,t3.*t14+t2.*t6.*t8,0.0,-t3.*t4+t2.*t5.*t6,-t6.*t12-t2.*t3.*t9,-t6.*t14+t2.*t3.*t8,0.0,t2.*(-1.0./5.0e1)+t4.*(9.2e1./5.0)-t2.*t5.*(2.4e1./2.5e1)-t2.*t7.*(9.0./1.0e2)+t4.*t6.*2.6e1+t2.*t3.*t5.*2.6e1+1.033e1,t8.*(-1.0./2.5e1)-t9.*(7.0./1.0e2)+t2.*t9.*(9.2e1./5.0)+t4.*t9.*(1.0./5.0e1)-t5.*t8.*(9.0./1.0e2)-t3.*t12.*2.6e1+t7.*t8.*(2.4e1./2.5e1)+t2.*t6.*t9.*2.6e1+t4.*t5.*t9.*(2.4e1./2.5e1)+t4.*t7.*t9.*(9.0./1.0e2)-4.3e1./1.0e2,t8.*(7.0./1.0e2)-t9.*(1.0./2.5e1)-t2.*t8.*(9.2e1./5.0)-t4.*t8.*(1.0./5.0e1)-t5.*t9.*(9.0./1.0e2)+t7.*t9.*(2.4e1./2.5e1)-t3.*t14.*2.6e1-t2.*t6.*t8.*2.6e1-t4.*t5.*t8.*(2.4e1./2.5e1)-t4.*t7.*t8.*(9.0./1.0e2)+3.23e2./2.5e1,1.0],[4, 4]);
